### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by KarnSaheb** [BelledonneCommunications/linphone-wp#1]
Opening the solution with Visual Studio after cloning the project produces references to unavailable files in the Agents Project. Files are RegistrationHelper.cs, Version.cs, VideoRenderer.cs, VideoStreamSource.cs.

**Comment by Gui13** [comment]
You forgot to clone recursively, so you're missing the submodules.
Also, RegistrationHelper.cs and Version.cs are generated at first compilation.
